[phases.setup]
aptPkgs = ["ffmpeg", "ffmpegthumbnailer"]

[phases.install]
cmds = [
    "which ffmpeg",
    "which ffprobe",
    "ffmpeg -version",
    "ffprobe -version",
    "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python main.py"
